# azure-pipelines-app.yaml

trigger:
  paths:
    include:
      - ansible/**
  branches:
    include:
      - main

stages:
  - stage: DeployApp
    displayName: "Deploy Application Code via Ansible"
    jobs:
      - job: App_Deployment
        displayName: "Run Ansible Playbook to Deploy App"
        pool:
          name: "self-hosted-agent-pool"

        steps:
          # - script: |
          #     sudo apt update
          #     sudo apt install -y ansible sshpass
          #   displayName: "Install Ansible & SSH dependencies"

          - task: DownloadSecureFile@1
            name: download_ssh_key
            inputs:
              secureFile: "id_rsa"

          - script: |
              mkdir -p ~/.ssh
              cp $(download_ssh_key.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "StrictHostKeyChecking no" > ~/.ssh/config
            displayName: "Setup SSH Private Key"

          # - task: CmdLine@2

          - script: |
              ansible-playbook -i inventory.ini site.yml --ssh-extra-args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
            displayName: "Run Ansible Playbook"
            workingDirectory: $(System.DefaultWorkingDirectory)/azure_epicbook/ansible
            env:
              ANSIBLE_HOST_KEY_CHECKING: "False"
