trigger:
  paths:
    include:
      - azure_epicbook/terraform/**
  branches:
    include:
      - main

stages:

- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      name: 'self-hosted-agent-pool'
    steps:

    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'id_rsa.pub'

    - script: |
        echo "Copying SSH public key into Terraform module"

        mkdir -p ~/.ssh
        cp $(download_ssh_key.secureFilePath) ~/.ssh/id_rsa.pub

        # Now copy into Terraform path
        # cp $(download_ssh_key.secureFilePath) terraform/id_rsa.pub

        # echo "Listing contents of terraform/"
        # ls -al terraform/
      displayName: 'Extract SSH Public Key for Terraform'

    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan and Apply'
      inputs:
        azureSubscription: 'it-azure-connection'
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/azure_epicbook/terraform/
        inlineScript: |
          echo "##[group]Terraform Init/Plan/Apply"
          terraform init -input=false 
          terraform plan -input=false -var-file="terraform.tfvars"
          terraform apply -input=false -auto-approve -var-file="terraform.tfvars"
          echo "##[endgroup]"